export const appRoutes = {
  home: "/",
  signIn: "/signin",
  signUp: "/signup",
  movies: "/movies",
  theatres: "/theatres",
  shows: "/shows",
  bookings: "/bookings",
  payments: "/payments",
  resetPassword: "/reset-password",
  adminMovies: "/admin/movies",
  adminCreateMovie: "/admin/movies/create",
  adminEditMovie: (movieId: string) => `/admin/movies/${movieId}/edit`,
  adminTheatres: "/admin/theatres",
  adminCreateTheatre: "/admin/theatres/create",
  adminEditTheatre: (theatreId: string) => `/admin/theatres/${theatreId}/edit`,
  adminShows: "/admin/shows",
  adminCreateShow: "/admin/shows/create",
  adminEditShow: (showId: string) => `/admin/shows/${showId}/edit`,
  adminUsers: "/admin/users",
  movieDetails: (movieId: string) => `/movies/${movieId}`,
  showBooking: (showId: string) => `/shows/${showId}/book`,
  bookingPayment: (bookingId: string) => `/bookings/${bookingId}/payment`
};
